import Head from "next/head";
import Link from "next/link";

const getUsers = () => {
  return new Promise(async (resolve) => {
    const res = await fetch(`https://reqres.in/api/users`);
    const details = await res.json();
    setTimeout(() => {
      resolve(details);
    }, 3000);
  });
};

export async function getServerSideProps() {
  // Fetch data from external API
  const users = await getUsers();
  // Pass data to the page via props
  return { props: { users } };
}

export default function UserDetails({ users }) {
  const data = users?.data || [];
  return (
    <>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data && data.length > 0 && (
        <div
          style={{
            height: "70vh",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <ul>
            {Array.isArray(data) &&
              data.map((user) => {
                return (
                  <>
                    <li>
                      <a href={`/user-details?id=${user.id}`}>
                        {user.first_name}
                      </a>
                    </li>
                  </>
                );
              })}
          </ul>
        </div>
      )}
    </>
  );
}
